language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby
matrix:
  allow_failures:
    - rvm: rbx-18mode
    - rvm: rbx-19mode
branches:
  only:
    - master
before_script:
  - sudo apt-get -y install ragel
